packages:
  - apps/nuxt
  - common/database
  - common/utils
  - common/validation
  - workers/*

catalog:
  drizzle-orm: 0.44.7
  typescript: 5.9.3
  valibot: 1.2.0
  wrangler: 4.50.0

cleanupUnusedCatalogs: true

nodeLinker: hoisted

saveExact: true
