packages:
  - apps/nuxt
  - common/database
  - common/utils
  - common/validation
  - workers/*

catalog:
  typescript: 5.9.2
  valibot: 1.1.0
  wrangler: 4.31.0

nodeLinker: hoisted

saveExact: true
