name: Database migration (production)

on:
  push:
    branches:
      - master
    paths:
      - 'common/database/migrations/**'

jobs:
  migration:
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm --filter @starter/database install
      - name: Run database migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm --filter @starter/database run db:migrate
